# Introduction to Pandas

In this section of the course we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. In this section of the course, you should go through the notebooks in this order:

* Objects
    * Series
    * DataFrames
* Missing Data
* Operations
    * apply()
    * lambda expression
* Data Analysis
    * GroupBy
    * Merging,Joining,and Concatenating
* Data Input and Output

## 2. Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

### Dropping missing data 

**df.dropna()** drops all rows with missing values

**df.dropna(axis=1)** drops all cokumns with missing data

**df.dropna(thresh=2)** drops all rows with 2 or more missing values

**df.dropna(inplace=True)** drops all rows in current dataframe object

*Also works for values in a single column **df['col'].dropna()**

In [ ]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

### Filling in missing data

**df.fillna(value=5)** fills in all locations with missing values

*Also works for a single column **df['col'].fillna(value=12)**

In [ ]:
df.fillna(value='FILL VALUE')

            A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

#  

We should fill in the data for individual column with a more meaningful value. In the next example the locations that do not contain a value we are setting the value to the average of all the other values in the same column.

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Great Job