# Introduction to Pandas

In this section of the course we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. In this section of the course, you should go through the notebooks in this order:

* DataTypes
    * Series
    * DataFrames
* Missing Data
* Operations
* Data Analysis
    * GroupBy
    * Merging, Joining, and Concatenating
    * Operations
* Data Input and Output

# Series

The first main data type we will learn about for pandas is the Series data type. Let's import Pandas and explore the Series object.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

In [2]:
import numpy as np
import pandas as pd

### Creating a Series

You can convert a list, numpy array, or dictionary to a Series:

In [3]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

Creating a Series from a **list**, using default indexing

In [ ]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

Creating a Series from a list, using define indices

In [ ]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

Creating a Series from an **array**

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

Creating a Series from a **dict**. Value and indices are defined in the dictionary.

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

In [ ]:
pd.Series(data=labels) #Values are strings

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series([sum,print,len]) #Values are functions

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

**Convert the type of value in a Series**

**series.astype(new_type)** outputs a Series with the same data converted to another object type

types could be **str, float, int32, int64, **etc

In [ ]:
pd.Series(data=arr).astype(int)

0    10
1    20
2    30
dtype: int64

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a several Series objects put together to share the same index. DataFrames have column headers in order to uniquely reference each Series object. Let's use pandas to explore this topic!

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from numpy.random import randn

In [ ]:
index_list  = 'A B C D E'.split() #Splits the string into a list of letters
column_list = 'W X Y Z'.split()

df = pd.DataFrame(randn(5,4), index=index_list, columns=column_list)
df

          W         X         Y         Z
A -0.247911  0.561792 -0.535653 -1.257791
B -0.110507 -0.006462  0.541659  2.166587
C  0.677772 -0.302449 -0.692805 -0.023263
D -0.762632 -1.107113  0.103257  0.343941
E -2.208982  1.279053 -0.166926  0.156191

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

Grab a single column from the DataFrame. Notice the output is a Series object!

In [ ]:
df['Z']

A   -1.257791
B    2.166587
C   -0.023263
D    0.343941
E    0.156191
Name: Z, dtype: float64

In [ ]:
type(df['Z'])

pandas.core.series.Series

Sometimes you may see colums refernced using **df.column**. This is the old way of doing this. Moving forward you should use **df['column']** to reference a column in a DataFrame object.

In [ ]:
df.Z

A   -1.257791
B    2.166587
C   -0.023263
D    0.343941
E    0.156191
Name: Z, dtype: float64

Select multiple columns. Notice we are using a list to index and the output is a DataFrame object.

In [ ]:
df[['W','Z']] # Pass a list of column names

          W         Z
A -0.247911 -1.257791
B -0.110507  2.166587
C  0.677772 -0.023263
D -0.762632  0.343941
E -2.208982  0.156191

**Creating a new column:**

Set a Series object or array with the same number of items.

prior["product_id"].astype(str)

In [ ]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A -0.247911  0.561792 -0.535653 -1.257791 -0.783564
B -0.110507 -0.006462  0.541659  2.166587  0.431152
C  0.677772 -0.302449 -0.692805 -0.023263 -0.015033
D -0.762632 -1.107113  0.103257  0.343941 -0.659375
E -2.208982  1.279053 -0.166926  0.156191 -2.375908

** Removing Rows and Columns**

**df.drop('row')** returns a DataFrame with a row removed. Notice original df object does not change.

**df.drop('column', axis=1)** removes a column from the DataFrame. If axis=0, a row will be removed. If you input a column name and set axis=0 it will fail. If you input a row index and set axis=1 it will fail. 

**df.drop('row', inplace=True)** removes a row from current df object. does not return anything.

In [ ]:
df2 = df.drop('new',axis=1)
df2

          W         X         Y         Z
A -0.247911  0.561792 -0.535653 -1.257791
B -0.110507 -0.006462  0.541659  2.166587
C  0.677772 -0.302449 -0.692805 -0.023263
D -0.762632 -1.107113  0.103257  0.343941
E -2.208982  1.279053 -0.166926  0.156191

Original df object did not change.

In [ ]:
df

          W         X         Y         Z       new
A -0.247911  0.561792 -0.535653 -1.257791 -0.783564
B -0.110507 -0.006462  0.541659  2.166587  0.431152
C  0.677772 -0.302449 -0.692805 -0.023263 -0.015033
D -0.762632 -1.107113  0.103257  0.343941 -0.659375
E -2.208982  1.279053 -0.166926  0.156191 -2.375908

In [ ]:
df.drop('new', axis=1, inplace=True)
df

          W         X         Y         Z
A -0.247911  0.561792 -0.535653 -1.257791
B -0.110507 -0.006462  0.541659  2.166587
C  0.677772 -0.302449 -0.692805 -0.023263
D -0.762632 -1.107113  0.103257  0.343941
E -2.208982  1.279053 -0.166926  0.156191

**Transpose** outputs a DataFame with columns and rows switched

In [ ]:
df.transpose()

          A         B         C         D         E
W -0.247911 -0.110507  0.677772 -0.762632 -2.208982
X  0.561792 -0.006462 -0.302449 -1.107113  1.279053
Y -0.535653  0.541659 -0.692805  0.103257 -0.166926
Z -1.257791  2.166587 -0.023263  0.343941  0.156191

###  Selecting Rows

**df.loc['row']**  selects a row by index. Notice output is a Series object with the columns as indices!

**df.iloc[number]** selects a row by position instead of index.

In [ ]:
df['W']      #Select a column
df.loc['A']  #Select a row

W   -0.247911
X    0.561792
Y   -0.535653
Z   -1.257791
Name: A, dtype: float64

In [ ]:
df.iloc[2]

W    0.677772
X   -0.302449
Y   -0.692805
Z   -0.023263
Name: C, dtype: float64

### Selecting subset of rows and columns

**df.loc['row','column']** output value at that location.

**df.loc[['row1','row2'],['column1','column2']]** if you provide a list of rows and columns, the output is a new DataFame that contains only the rows and columns selected, in the same order as the input lists.

In [ ]:
df.loc['B','Y']

0.541659183700414

In [ ]:
df.loc[['C','B'],['Y','W']]

          Y         W
C -0.692805  0.677772
B  0.541659 -0.110507

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation. Instead of selecting values in a DataFrame based on location, we will select values based on a condition.

In [ ]:
df>0 # (Our condition) All values greater than zero. Returns a True/False DataFrame

       W      X      Y      Z
A  False   True  False  False
B  False  False   True   True
C   True  False  False  False
D  False  False   True   True
E  False   True  False   True

In [ ]:
df[df>0] # Indexing using Our Condition

          W         X         Y         Z
A       NaN  0.561792       NaN       NaN
B       NaN       NaN  0.541659  2.166587
C  0.677772       NaN       NaN       NaN
D       NaN       NaN  0.103257  0.343941
E       NaN  1.279053       NaN  0.156191

###  
Conditioning based on values in column.

In [ ]:
df['W']>0 # (Our Condition) It returns a True/False Series object.

A    False
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [ ]:
df[df['W']>0] # Indexing using Our Condition.

          W         X         Y         Z
C  0.677772 -0.302449 -0.692805 -0.023263

Notice fewer rows. All rows that were False based on Our Condition are not present in the output DataFrame. It is possible to have a DataFrame with no rows.

Since the output is a DataFrame we can perform operations on it like any other DataFrame.

In [ ]:
df[df['W']>0]['Y'] # Indexing using Our Condition and observing a single column.

C   -0.692805
Name: Y, dtype: float64

In [ ]:
df[df['W']>0][['Y','X']]

          Y         X
C -0.692805 -0.302449

When applying multiple conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']<0) & (df['Y'] > 0)][['Y','W']]

          Y         W
B  0.541659 -0.110507
D  0.103257 -0.762632

### More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

**df.reset_index()** resets to default 0,1...n. A new column 'index' is generated containing the original indices.

In [ ]:
df.reset_index()

  index         W         X         Y         Z
0     A -0.247911  0.561792 -0.535653 -1.257791
1     B -0.110507 -0.006462  0.541659  2.166587
2     C  0.677772 -0.302449 -0.692805 -0.023263
3     D -0.762632 -1.107113  0.103257  0.343941
4     E -2.208982  1.279053 -0.166926  0.156191

Setting new indices on your DataFrame.
**df.set_index('column')** outputs a new DataFrame with an existing column as the indices in the DataFrame.
**df.set_index('column', inplace=True)** replaces indices with existing column with

In [ ]:
newind = 'CA NY WY OR CO'.split() # List of State names
df['States'] = newind # Add list to new column in DataFrame
df.set_index('States',inplace=True)
df

               W         X         Y         Z
States
CA     -0.247911  0.561792 -0.535653 -1.257791
NY     -0.110507 -0.006462  0.541659  2.166587
WY      0.677772 -0.302449 -0.692805 -0.023263
OR     -0.762632 -1.107113  0.103257  0.343941
CO     -2.208982  1.279053 -0.166926  0.156191

**Rename rows or columns using df.rename()** 

**df.rename(columns = {"current_name" : "new_name"})** replaces the name of a column

**df.rename(index = {"current_name1" : "new_name1"}, inplace=True)** replaces the index of a row

In [ ]:
df.rename(columns = {"Z" : "A"})

               W         X         Y         A
States
CA     -0.247911  0.561792 -0.535653 -1.257791
NY     -0.110507 -0.006462  0.541659  2.166587
WY      0.677772 -0.302449 -0.692805 -0.023263
OR     -0.762632 -1.107113  0.103257  0.343941
CO     -2.208982  1.279053 -0.166926  0.156191

Note: It is important to understand the outputs of the functions. As you become more comfortable you will begin calling multiple functions in a row. Knowing if you are expecting to recieve a Series, DataFrame or specific value as an output is important. If you aren't careful, you may run into errors.

# Great Job!