**If you haven't already, please hit :**

`File` -> `Save a Copy in Drive`

**Copy this notebook to your Google drive, and work on a copy. If you don't do this, your changes won't be saved!**

# SF Salaries Exercise

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

Follow steps 1-3 [here](https://www.analyticsvidhya.com/blog/2021/06/how-to-load-kaggle-datasets-directly-into-google-colab/) before beginning. This will help you get a bit familiar with Kaggle Datasets.

In [ ]:
! pip install -q kaggle
! mkdir ~/.kaggle

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kaggle/sf-salaries")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'sf-salaries' dataset.
Path to dataset files: /kaggle/input/sf-salaries

In [ ]:
!unzip sf-salaries.zip

Archive:  sf-salaries.zip
replace Salaries.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: Salaries.csv
replace database.sqlite? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: database.sqlite

**Import pandas as pd. Import numpy as np.**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Read Salaries.csv as a dataframe called sal.**

In [ ]:
sal = pd.read_csv("/kaggle/input/sf-salaries/Salaries.csv")
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

/tmp/ipython-input-3673340814.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv("/kaggle/input/sf-salaries/Salaries.csv")

**Check the head of the DataFrame.**

In [ ]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**Use the .info() method to find out how many entries there are.**

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

**What is the average BasePay?**

In [ ]:
sal["BasePay"] = pd.to_numeric(sal["BasePay"], errors="coerce")
sal["BasePay"].mean()

np.float64(66325.4488404877)

**What is the highest amount of OvertimePay in the dataset ?**

In [ ]:
sal["OvertimePay"] = pd.to_numeric(sal["OvertimePay"], errors="coerce")
sal["OvertimePay"].max()

245131.88

**What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).**

In [ ]:
sal[sal["EmployeeName"] == "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

**How much does JOSEPH DRISCOLL make (including benefits)?**

In [ ]:
sal[sal["EmployeeName"] == "JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

**What is the name of highest paid person (including benefits)?**

In [ ]:
sal.loc[sal["TotalPayBenefits"].idxmax()]["EmployeeName"]

'NATHANIEL FORD'

**What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [ ]:
sal.loc[sal["TotalPayBenefits"].idxmin()][["EmployeeName", "TotalPayBenefits"]]

EmployeeName        Joe Lopez
TotalPayBenefits      -618.13
Name: 148653, dtype: object

**What was the average (mean) BasePay of all employees per year? (2011-2014)?**

In [ ]:
sal.groupby("Year")["BasePay"].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

**How many unique job titles are there?**

In [ ]:
sal["JobTitle"].nunique()

2159

**What are the top 5 most common jobs?**

In [ ]:
sal["JobTitle"].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

**How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?)**

In [ ]:
sal_2013 = sal[sal["Year"] == 2013]
sal_2013["JobTitle"].value_counts()[sal_2013["JobTitle"].value_counts() == 1].count()

np.int64(202)

**How many people have the word Chief in their job title? (This is pretty tricky)**

In [ ]:
sal["JobTitle"].str.contains("Chief", case=False, na=False).sum()

np.int64(627)

**Bonus: Is there a correlation between length of the Job Title string and Salary?**

In [ ]:
sal["JobTitleLength"] = sal["JobTitle"].str.len()

# Great Job!